/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as EssayRouteImport } from './routes/essay'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatThreadIdRouteImport } from './routes/chat.$threadId'

const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const EssayRoute = EssayRouteImport.update({
  id: '/essay',
  path: '/essay',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/chat': typeof ChatRouteWithChildren
  '/essay': typeof EssayRoute
  '/progress': typeof ProgressRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/chat': typeof ChatRouteWithChildren
  '/essay': typeof EssayRoute
  '/progress': typeof ProgressRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/chat': typeof ChatRouteWithChildren
  '/essay': typeof EssayRoute
  '/progress': typeof ProgressRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyze'
    | '/chat'
    | '/essay'
    | '/progress'
    | '/chat/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analyze' | '/chat' | '/essay' | '/progress' | '/chat/$threadId'
  id:
    | '__root__'
    | '/'
    | '/analyze'
    | '/chat'
    | '/essay'
    | '/progress'
    | '/chat/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzeRoute: typeof AnalyzeRoute
  ChatRoute: typeof ChatRouteWithChildren
  EssayRoute: typeof EssayRoute
  ProgressRoute: typeof ProgressRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/essay': {
      id: '/essay'
      path: '/essay'
      fullPath: '/essay'
      preLoaderRoute: typeof EssayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$threadId': {
      id: '/chat/$threadId'
      path: '/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
  }
}

interface ChatRouteChildren {
  ChatThreadIdRoute: typeof ChatThreadIdRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatThreadIdRoute: ChatThreadIdRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzeRoute: AnalyzeRoute,
  ChatRoute: ChatRouteWithChildren,
  EssayRoute: EssayRoute,
  ProgressRoute: ProgressRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
